-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_sms_message`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_sms_message
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_sms_message` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique SmsMessage ID',
  `mailing_id` int unsigned COMMENT 'Mailing ID',
  `message_id` int unsigned COMMENT 'Message ID',
  `contact_id` int unsigned COMMENT 'Contact ID',
  `message` text NOT NULL COMMENT 'Message to send',
  `number` text NOT NULL COMMENT 'Phone number',
  `is_send` tinyint DEFAULT 0 COMMENT 'Already send?',
  `date_send` datetime DEFAULT null COMMENT 'When send',
  `is_delivered` tinyint DEFAULT 0 COMMENT 'Already delivered?',
  `date_delivered` datetime DEFAULT null COMMENT 'When delivered',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
